default_language_version:
  python: python3

ci:
  autofix_prs: false
  autofix_commit_msg: '[pre-commit.ci] Fixing issues with pre-commit'
  autoupdate_commit_msg: '[pre-commit.ci] autoupdate'
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.5.1  # Black version
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
  # - repo: local
  #   hooks:
  #     - id: autofix
  #       name: autofix
  #       entry: bash runtests.sh --autofix
  #       language: python
  #       types: [python]
  #       pass_filenames: false
  #       additional_dependencies: ["black>=25.1.0"]
