name: Auto-Update PRs

on:
  push:
    branches:
      - main # Change to your primary target branch (e.g., dev)
  workflow_dispatch: # Allows manual triggering if needed

permissions:
  contents: write
  pull-requests: write

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetches all history so branches can be merged locally

      - name: Update the oldest PR which is approved and automerging-enabled
        run: |
          # Find all open PRs targeting this branch which are open and approved
          PR_DATA=$(gh pr list --state open --search 'review:approved' --base ${{ github.ref_name }} --json number,reviewDecision,autoMergeRequest)

          # if the search criteria doesn't work then take the first 200 open PRs
          if [ "$PR_DATA" == "[]" ]
          then
            PR_DATA=$(gh pr list --state open -L 200 --base ${{ github.ref_name }} --json number,reviewDecision,autoMergeRequest)
          fi

          echo '================================'
          echo "PR_DATA:"
          echo $PR_DATA
          echo '================================'

          # select the oldest open approved PR with automerge enabled
          OLDEST_APPROVED=$(echo $PR_DATA | jq -r '.[] | select(.reviewDecision == "APPROVED") | select(.autoMergeRequest != null) | "\(.number)"'|head -n 1)

          if [ -z "$OLDEST_APPROVED" ]
          then
            echo "No approved PRs to update."
          else
            echo "Updating PR $OLDEST_APPROVED ..."
            gh pr update-branch "$OLDEST_APPROVED" || echo "Failed to update PR #$OLDEST_APPROVED (merge conflicts?)."
          fi
