# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  # automatically cancel the previously triggered workflows when there's a newer version
  group: ci-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # This job will set its output value `skip` to 2 if only documentation was changed, either documentation files or
  # the docstrings of source files. If any source lines are changed, or non-documentation files are changed, the
  # result is 0 which then triggers tests to run. This job works by using the compare_sources.py script to compare
  # changed files to see if they differ in ways other than comments or docstrings.
  test_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-changes.outputs.skip }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 2
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Check File Changes
      id: check-changes
      shell: bash
      run: |
        echo "skip=1" >> $GITHUB_OUTPUT
        mkdir -p /tmp/check_changes
        git diff --name-only HEAD^..HEAD ':!docs' | while read i
        do
          echo "Checking for changes: $i"
          if ! git show HEAD^:$i > /tmp/check_changes/$(basename $i)
          then
            echo "New file found, or 'git show' failed, running tests."
          elif ! python ./compare_sources.py $i /tmp/check_changes/$(basename $i)
          then
            echo "Change found, running tests."
          else
            continue
          fi

          echo "skip=0" >> $GITHUB_OUTPUT
          break
        done

  test:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    timeout-minutes: 40
    needs: test_skip

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      if: needs.test_skip.outputs.skip == 0
      with:
        fetch-depth: 2
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      if: needs.test_skip.outputs.skip == 0
      with:
        python-version: "3.12"
    - name: Install dependencies
      if: needs.test_skip.outputs.skip == 0
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      if: needs.test_skip.outputs.skip == 0
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
